### ISSUE TITLE
Usage of com.ealva:ealvalog:0.5.6-SNAPSHOT

### ISSUE THREAD

**Issue by ReIaxo** [pandasys/eAlvaBrainz#1]
Hi. I want to try your music brainz api client but when i include it in my android project, i get this error: 

Failed to resolve: com.ealva:ealvalog:0.5.6-SNAPSHOT

A look in the maven repo shows, that there is no 0.5.6-SNAPSHOT version. Maybe you missed to release Version 5.6.0 of ealvalog?

EDIT: com.ealva:ealvalog-core:0.5.6-SNAPSHOT is also missing

**Comment by pandasys** [comment]
I'll take a look asap. Probably tomorrow. Sorry about that.

-------- Original Message --------

**Comment by pandasys** [comment]
Sorry it took so long, very busy at work.

I have an app which uses these libraries and the dependencies are found. Here's the relevant declarations:
```
  object EAlvaBrainz {
    private const val VERSION = "0.10.3-0"
    const val BRAINZ = "com.ealva:ealvabrainz:$VERSION"
    const val BRAINZ_SERVICE = "com.ealva:ealvabrainz-service:$VERSION"
  }

  object EAlvaLog {
    private const val VERSION = "0.5.6-SNAPSHOT"
    const val EALVALOG = "com.ealva:ealvalog:$VERSION"
    const val ANDROID = "com.ealva:ealvalog-android:$VERSION"
    const val CORE = "com.ealva:ealvalog-core:$VERSION"
  }
```

In build.gradle.kts at project level, ensure you include the snapshot respository:
```
allprojects {
  repositories {
    maven { setUrl("https://jitpack.io") }
    google()
    mavenCentral()
    maven(url = "https://oss.sonatype.org/content/repositories/snapshots/")
  }
}

```
When I search at oss.sonatype.org I see the 0.5.6.SNAPSHOT library.

**Comment by pandasys** [comment]
This app https://github.com/pandasys/toque uses the libraries. These, app and libs, haven't been updated in some time. After including the snapshots repository please reopen if this is still an issue.

**Comment by ReIaxo** [comment]
Thank you for helping with this. Adding the snapshot sonatype repo helps out. 

I searched here: https://mvnrepository.com/artifact/com.ealva

Maybe its helpful to add the repository information to the great guide in readme.md.
